--- 
title: "Introduction to R for Biologists"
author: "Alana Schick"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
description: "This tutorial covers workshop material"
---

# Welcome

Workshop material will be added here as we go along. For each day of the workshop, the basic material will be uploaded and more details will be added based on your questions and problems we encounter. So please ask as many questions are you can to help us in making this workshop better!!

## Workshop Schedule

*Subject to change, depending how things go. 

### Day 1 {-}

Time | Topic                               
:-------| :----------------------------------
09:00  | Welcome
09:10  | 1. Introducing R and RStudio
09:40  | 2. Installing R packages
10:00  | 3. R Basics
10:30  | Break
10:45  | 3. R Basics - cont
11:15  | 4. Starting with Data
12:00  | Lunch break
13:00  | 5. Conditional statements and loops
13:30  | 6. Manipulating data in the tidyverse
14:30  | Break
14:45  | 6. Tidyverse - cont
15:30  | 7. Data visualization with ggplot2
16:00  | Finish

### Day 2 {-}

Time | Topic                                         
:-------| :----------------------------------
09:00  | Questions and review Day 1
09:15  | 7. Data visualization - cont
10:00  | 8. Project - task 1
10:30  | Break
10:45  | 8. Project - task 2
12:00  | Lunch break
13:00  | 8. Project - task 3
14:30  | Break
14:45  | 8. Project - task 4
15:30  | Review project and open discussion
15:55  | Survey!
16:00  | Finish

  
## Important links

- Datacamp: [link](https://www.datacamp.com/home)
  
<!-- - DADA2 Tutorial :  [link](http://benjjneb.github.io/dada2/tutorial.html)  -->
<!-- - Day One presentation : [link](microbiomeworkshop.pdf) -->
<!-- - Day One dataset : [link](MiSeqSOPData.zip) -->
<!-- - Project dataset : [link](https://www.dropbox.com/sh/qra6ohbsyt1icaz/AAACvlNjUhfkbkGIp_1KA2uCa?dl=0) -->
